apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: istio-system
data:
  redis.conf: |-
    protected-mode yes
    port 6379
    bind 0.0.0.0
    # Close the connection after a client is idle for N seconds (0 to disable)
    timeout 0

    tcp-keepalive 300


    daemonize no
    supervised no


    loglevel notice

    logfile ""

    always-show-logo no

    appendonly no
    save ""
