apiVersion: v1
kind: Service
metadata:
  name: ratelimit-redis
  namespace: istio-system
  labels:
    app: ratelimit-redis
    version: v1
spec:
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: ratelimit-redis
    version: v1
