apiVersion: v1
entries:
  ratelimiter-app:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-23T13:50:36.08852+02:00"
    description: A Helm Chart for Kubernetes
    digest: 1bd58234beba1f6e8ed8fd90a3661dc45b56d59d431c6ed7d0ac2909ae0bd128
    name: ratelimiter-app
    type: application
    urls:
    - ratelimiter-app-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-23T13:50:36.087367+02:00"
